# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tabb
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: 14.16.1

      - uses: actions/setup-java@v1
        with:
            java-version: '11.x'

      # Runs a single command using the runners shelll
      - name: Install node.js packages
        run: npm install

      - name: configure execution authorization
        run: chmod +x mvnw

      - name: execute java unit test
        run: npm run ci:backend:test

      - name: execute front unit test
        run: npm run ci:frontend:test

        # Prépare un .jar comme si il partait en prod
      - name: Create .jar file
        run: ./mvnw -ntp verify -DskipTests --batch-mode "-Pprod" "-Pe2e" "-Denforcer.skip=true"

        # Créé une BDD et lance le .jar dans un docker
      - name: create database and execute .jar file
        run: npm run ci:e2e:prepare:docker

        #Lance les tests
      - name: execute test
        run: npm run ci:e2e:run

        # Met fin au docker et nettoie le tout.
      - name: stop docker process
        run: npm run ci:e2e:teardown

      # - name: webdrive update
      #   run: npm run webdriver-manager update

      # - name: webdrive update
      #   run: npm run webdriver-manager start

      # # test for back end
      # - name: back_end test
      #   run: chmod +x mvnw && npm run ci:backend:test

      # # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
